[package]
name = "geminitranslator"
version = "0.1.0"
description = "A lightweight AI Translator"
authors = ["anhnn"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "geminitranslator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.0", features = ["tray-icon"] } # Kích hoạt tính năng System Tray
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] } # Để gọi API Gemini
tokio = { version = "1", features = ["full"] } # Xử lý bất đồng bộ (Async)
enigo = "0.1.2"
tauri-plugin-clipboard-manager = "2.3.2"
arboard = "3.6.1"
image = "0.25.10"
base64 = "0.22.1"
tauri-plugin-autostart = "2.5.1"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"

